---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maintainerr
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: maintainerr-secret
    creationPolicy: Owner
  data:
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: Jellyfin MUMC token/password
        property: password