---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: home-assistant
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: multus-networks
      namespace: network
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./clusters/psb/apps/home-automation/home-assistant/app"
  postBuild:
    substitute:
      APP: home-assistant
      APP_GID: "2000"
      APP_UID: "2000"
      VOLSYNC_CAPACITY: 8Gi
      VOLSYNC_CLAIM: home-assistant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: home-automation
  timeout: 5m
  wait: false
