---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm
    creationPolicy: Owner
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .master_key }}"
        NEURALWATT_API_KEY: "{{ .neuralwatt_api_key }}"
        OPENCODE_API_KEY: "{{ .opencode_api_key }}"
  dataFrom:
    - extract:
        key: litellm
    - extract:
        key: neuralwatt
      rewrite:
        - regexp:
            source: "(.*)"
            target: "neuralwatt_$1"
    - extract:
        key: opencode-go
      rewrite:
        - regexp:
            source: "(.*)"
            target: "opencode_$1"
