---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: litellm
        property: master key
    - secretKey: NEURALWATT_API_KEY
      remoteRef:
        key: neuralwatt
        property: api key
    - secretKey: OPENCODE_API_KEY
      remoteRef:
        key: opencode-go
        property: api key
