---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chartRef:
    kind: OCIRepository
    name: plex
  interval: 30m
  values:
    controllers:
      plex:
        pod:
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: plex-gpu
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.42.2.10156@sha256:9ad8a3506e1d8ebda873a668603c1a2c10e6887969564561be669efd65ae8871
            env:
              TZ: Europe/Prague
              PLEX_ADVERTISE_URL: https://plex.nebular-grid.space:443,http://10.1.6.63:32400,http://plex.media.svc.cluster.local:32400
              PLEX_NO_AUTH_NETWORKS: 10.244.0.0/16
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: &port 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 100m
              limits:
                memory: 16Gi
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.1.6.63
        externalTrafficPolicy: Local
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: plex
        advancedMounts:
          plex:
            app:
              - path: /config
      tmpfs:
        type: emptyDir
      media:
        type: nfs
        server: asc.internal
        path: /mnt/tank/media
        advancedMounts:
          plex:
            app:
              - path: /data/nas-media/movies
                subPath: movies
              - path: /data/nas-media/tv
                subPath: tv
    route:
      app:
        hostnames:
          - plex.nebular-grid.space
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - # Ref: https://forums.plex.tv/t/external-srt-subtitles-are-not-working-w-reverse-proxy/886540
            backendRefs:
              - identifier: app
                port: *port
            filters:
              - type: RequestHeaderModifier
                requestHeaderModifier:
                  remove:
                    - Range
            matches:
              - path:
                  type: PathPrefix
                  value: /library/streams
          - backendRefs:
              - identifier: app
                port: *port
