---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oneplay-server
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oneplay-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: NebularGrid/Oneplay
        property: username
    - secretKey: password
      remoteRef:
        key: NebularGrid/Oneplay
        property: password