---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.13.2
    digest: sha256:bfdfdcc45864cb7fd0c41368b26e0127470c10ea41d981756210899c225266a6
  url: oci://ghcr.io/immich-app/immich-charts/immich
