---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Ti
  nfs:
    path: /mnt/tank/stores/photos
    server: asc.internal
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeName: immich-library
