[env]
_.fnox-env = { tools = true }
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talosconfig"
KUBECONFIG = "{{config_root}}/kubeconfig"

[plugins]
fnox-env = "https://github.com/jdx/mise-env-fnox"

[tools]
actionlint = "1.7.12"
fnox = "1.19.0"
helm = "4.1.3"
helmfile = "1.4.4"
hk = "1.41.0"
kustomize = "5.8.1"
pkl = "0.31.1"
uv = "0.11.4"
yamlfmt = "0.21.0"
yamllint = "1.38.0"
yq = "4.52.5"
"github:mitsuhiko/minijinja[minijinja-cli]" = "2.19.0"

[settings.pipx]
uvx = true

[tasks.check]
description = "Run all checks"
run = "hk check --all"

[tasks.fix]
description = "Fix all issues"
run = "hk fix --all"
