---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparkyfitness
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sparkyfitness-secrets
    creationPolicy: Owner
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        SPARKY_FITNESS_API_ENCRYPTION_KEY: "{{ .API_ENCRYPTION_KEY }}"
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
  dataFrom:
    - extract:
        key: SparkyFitness
