---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
  data:
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: open-webui
        property: secret key
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: litellm
        property: master key
