---
apiVersion: v1
kind: Service
metadata:
  name: matter-server
  labels:
    app.kubernetes.io/name: matter-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: matter-server
  ports:
    - name: http
      port: 5580
      protocol: TCP
      targetPort: http
