---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: actual
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: actual
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/oidc
  dependsOn:
    - name: kopiur
      namespace: system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kanidm
      namespace: security
  interval: 1h
  path: "./clusters/psb/apps/selfhosted/actual/app"
  postBuild:
    substitute:
      APP: actual
      APP_NAMESPACE: selfhosted
      KOPIUR_CLAIM: actual-data
      OIDC_DISPLAY_NAME: Actual Budget
      OIDC_CALLBACK: /openid/callback
      OIDC_LEGACY_CRYPTO: "true"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
