---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sable
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: sable
  interval: 1h
  path: ./clusters/psb/apps/matrix/sable/app
  postBuild:
    substitute:
      APP: sable
      APP_NAMESPACE: matrix
      SUBDOMAIN: sable
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: matrix
  timeout: 5m
  wait: false
