---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: jellyfin
  components:
    - ../../../../components/gpu
    - ../../../../components/kopiur/backup
    - ../../../../components/zeroscaler/nas-nfs-scaler
    - ../../../../components/oidc
  dependsOn:
    - name: kopiur
      namespace: system
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: kanidm
      namespace: security
  interval: 1h
  path: "./clusters/psb/apps/media/jellyfin/app"
  postBuild:
    substitute:
      APP: jellyfin
      APP_NAMESPACE: media
      SUBDOMAIN: jf
      KOPIUR_CLAIM: jellyfin
      KOPIUR_CAPACITY: 10Gi
      OIDC_DISPLAY_NAME: "Jellyfin"
      OIDC_CALLBACK: /sso/OID/redirect/kanidm
      OIDC_ORIGIN: /sso/OID/start/kanidm
      OIDC_SHORT_USERNAME: "true"
      OIDC_CLAIM_MAPS: |
        {
          "roles": {
            "joinType": "array",
            "valuesByGroup": {
              "users@idm.nebular-grid.space": ["user"],
              "admins@idm.nebular-grid.space": ["admin"]
            }
          }
        }
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
