---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: jellyfin
  components:
    - ../../../../components/gpu
    - ../../../../components/kopiur/backup
    - ../../../../components/zeroscaler/nas-nfs-scaler
  dependsOn:
    - name: kopiur
      namespace: system
    - name: intel-gpu-resource-driver
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./clusters/psb/apps/media/jellyfin/app"
  postBuild:
    substitute:
      APP: jellyfin
      KOPIUR_CLAIM: jellyfin
      KOPIUR_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
