---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kromgo
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.15.2
    digest: sha256:00c087fa0b5b9abb595046f1091eaf870654a2e927875de1f208335645b42af2
  url: oci://ghcr.io/home-operations/charts/kromgo
