#!/usr/bin/env bash
#MISE description="Force sync a single ExternalSecret"
#USAGE arg "<namespace>" help="Namespace of the ExternalSecret"
#USAGE arg "<name>" help="Name of the ExternalSecret"
set -euo pipefail

kubectl -n "${usage_namespace}" annotate --field-manager flux-client-side-apply --overwrite \
  es "${usage_name}" \
  force-sync="$(date +%s)"
