---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-mcp
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: actual-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: ACTUAL_PASSWORD
      remoteRef:
        key: Actual Budget
        property: password
    - secretKey: ACTUAL_BUDGET_SYNC_ID
      remoteRef:
        key: Actual Budget
        property: sync id
