---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openebs
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.5.1
    digest: sha256:b74c651822ed1811360936bec24d2ee0fc073c1def1098e2399fd7de76c63dca
  url: oci://ghcr.io/openebs/charts/openebs
