---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: grafana-mcp
spec:
  alias: grafana_mcp
  workload:
    image: mcp/grafana:latest
    port: 8000
    env:
      - name: GRAFANA_URL
        value: http://grafana-service.observability.svc.cluster.local:3000
      - name: GRAFANA_SERVICE_ACCOUNT_TOKEN
        valueFrom:
          secretKeyRef:
            name: grafana-mcp-secret
            key: token
