---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sparkyfitness-frontend
spec:
  chartRef:
    kind: OCIRepository
    name: sparkyfitness-frontend
  interval: 30m
  values:
    controllers:
      sparkyfitness-frontend:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/codewithcj/sparkyfitness-frontend
              tag: v0.16.6.1
            env:
              SPARKY_FITNESS_SERVER_HOST: sparkyfitness.selfhosted.svc.cluster.local
              SPARKY_FITNESS_SERVER_PORT: "3010"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 15m
                memory: 64Mi
              limits:
                memory: 64Mi
    service:
      app:
        controller: sparkyfitness-frontend
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - fitness.nebular-grid.space
        parentRefs:
          - name: envoy-internal
            namespace: network
