---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sparkyfitness
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: sparkyfitness
  components:
    - ../../../../components/volsync
    - ../../../../components/postgres/pass
    - ../../../../components/postgres/patch
  dependsOn:
    - name: postgres-cluster
      namespace: database
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./clusters/psb/apps/selfhosted/sparkyfitness/server"
  postBuild:
    substitute:
      APP: sparkyfitness
      VOLSYNC_CLAIM: sparkyfitness-uploads
      VOLSYNC_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sparkyfitness-frontend
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: sparkyfitness
  dependsOn:
    - name: sparkyfitness
  interval: 1h
  path: "./clusters/psb/apps/selfhosted/sparkyfitness/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
