---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tracearr-secret
    creationPolicy: Owner
    template:
      data:
        JWT_SECRET: "{{ .tracearr_jwt_secret }}"
        COOKIE_SECRET: "{{ .tracearr_cookie_secret }}"
        TIMESCALEDB_PASSWORD: "{{ .tracearr_db_password }}"
        DATABASE_URL: "postgresql://tracearr:{{ .tracearr_db_password }}@tracearr-timescaledb.media.svc.cluster.local:5432/tracearr"
  dataFrom:
    - extract:
        key: Tracearr
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "tracearr_$1"
