---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actual
spec:
  chartRef:
    kind: OCIRepository
    name: actual
  interval: 30m
  values:
    controllers:
      actual:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 2000
            runAsUser: 2000

        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 26.9.0@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3
            env:
              ACTUAL_PORT: &httpPort 5006
              ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: 80
              NODE_OPTIONS: --max-old-space-size=768
              # Kanidm OIDC SSO
              ACTUAL_OPENID_DISCOVERY_URL: https://idm.nebular-grid.space/oauth2/openid/actual/.well-known/openid-configuration
              ACTUAL_OPENID_CLIENT_ID:
                secretKeyRef:
                  name: kanidm-actual-oidc
                  key: client-id
              ACTUAL_OPENID_CLIENT_SECRET:
                secretKeyRef:
                  name: kanidm-actual-oidc
                  key: client-secret
              ACTUAL_OPENID_SERVER_HOSTNAME: https://actual.nebular-grid.space
              ACTUAL_OPENID_ENFORCE: "true"
              ACTUAL_USER_CREATION_MODE: login
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 1Gi

    service:
      app:
        ports:
          http:
            port: *httpPort

    persistence:
      data:
        existingClaim: actual-data
        advancedMounts:
          actual:
            app:
              - path: /data

    route:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        hostnames:
          - actual.nebular-grid.space
        parentRefs:
          - name: envoy-internal-public-dns
            namespace: network
