---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  chartRef:
    kind: OCIRepository
    name: sabnzbd
  interval: 30m
  values:
    controllers:
      sabnzbd:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |-
              [{
                "name": "multus-vpn",
                "namespace": "network",
                "ips": ["10.1.5.11/24"],
                "mac": "2a:6f:c9:1d:3b:87"
              }]
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sabnzbd
              tag: 4.5.5
            env:
              SABNZBD__PORT: &port 8080
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                sabnzbd.nebular-grid.space
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 5m
                memory: 1Gi
              limits:
                memory: 12Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: sabnzbd-config
        advancedMounts:
          sabnzbd:
            app:
              - path: /config
      downloads:
        type: nfs
        path: /mnt/tank/media
        server: asc.internal
        globalMounts:
          - path: /data/nas-media/downloads/sabnzbd
            subPath: downloads/sabnzbd
      ephemeral:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: "openebs-hostpath"
                resources:
                  requests:
                    storage: 100Gi
        advancedMounts:
          sabnzbd:
            app:
              - path: /incomplete
                subPath: incomplete
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /config/logs
            subPath: logs
          - path: /tmp
            subPath: tmp
    route:
      app:
        hostnames:
          - sabnzbd.nebular-grid.space
        parentRefs:
          - name: envoy-internal
            namespace: network
