---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  chartRef:
    kind: OCIRepository
    name: multus
  interval: 30m
  values:
    cni-plugins:
      image:
        repository: ghcr.io/home-operations/cni-plugins
        tag: 1.9.1@sha256:8ed5338f49966ca08b79d4ca754bc16af449b5375867f922890a680da2a4402d
    multus:
      image:
        repository: ghcr.io/k8snetworkplumbingwg/multus-cni
        tag: v4.3.0@sha256:ec4e5dfe12b675e4dcbf4e9cd14892f7b4c8ac27aa0dc93cf2e9be0bdd7d764a
      resources:
        requests:
          cpu: 10m
        limits:
          memory: 32Mi
    cni:
      netPath: /etc/cni/net.d
      binPath: /opt/cni/bin
