---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.0
    digest: sha256:5ce7e1ef30a218264f6095f09f4d659e6a7d872fb310cefff87ee86dc305f2bb
  url: oci://ghcr.io/home-operations/charts/kopiur
