---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-secret"
    creationPolicy: Owner
    template:
      data:
        KOPIA_FS_PATH: /repository
        KOPIA_PASSWORD: "{{ .kopia_password }}"
        KOPIA_REPOSITORY: filesystem:///repository
  data:
    - secretKey: kopia_password
      remoteRef:
        key: Kopia
        property: password
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync-minio"
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-minio"
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .minio_url }}/${APP}"
        RESTIC_PASSWORD: "{{ .restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ .minio_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .minio_secret_key }}"
  data:
    - secretKey: minio_access_key
      remoteRef:
        key: Volsync Minio bucket
        property: access key id
    - secretKey: minio_secret_key
      remoteRef:
        key: Volsync Minio bucket
        property: secret access key
    - secretKey: minio_url
      remoteRef:
        key: Volsync Minio bucket
        property: url
    - secretKey: restic_password
      remoteRef:
        key: Volsync Minio bucket
        property: restic password
