---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: conduwuit-config
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: conduwuit-config
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: conduwuit-configmap
            items:
              - key: conduwuit.toml
  dataFrom:
    - extract:
        key: conduwuit
