---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: conduwuit
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: conduwuit-secret
    creationPolicy: Owner
    template:
      data:
        CONDUWUIT_ALLOW_REGISTRATION: "true"
        CONDUWUIT_REGISTRATION_TOKEN: "{{ .registration_token }}"
  data:
    - secretKey: registration_token
      remoteRef:
        key: conduwuit
        property: registration token
