---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-exporter
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.58.0
    digest: sha256:90c81a07f2d2418d4ce356ea2863d28fc9dfd0ed2effc0cac7f3cec7a9e68642
  url: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
