---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: obsidian-livesync
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: obsidian-livesync-secret
    creationPolicy: Owner
  data:
    - secretKey: OBSIDIAN_AUTH_TOKEN
      remoteRef:
        key: obsidian-livesync
        property: auth token
    - secretKey: VAULT_NAME
      remoteRef:
        key: obsidian-livesync
        property: vault name
    - secretKey: VAULT_PASSWORD
      remoteRef:
        key: obsidian-livesync
        property: vault password
