---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../components/flux-alerts
resources:
  - ./namespace.yaml
  - ./open-webui/ks.yaml
  - ./litellm-operator/ks.yaml
  - ./litellm/ks.yaml
  - ./text-embeddings-inference/ks.yaml
  - ./llmkube/ks.yaml
  - ./memini/ks.yaml
  - ./mcp/searxng-mcp/ks.yaml
  - ./mcp/context7-mcp/ks.yaml
  - ./mcp/github-mcp/ks.yaml
  - ./mcp/ha-mcp/ks.yaml
  - ./mcp/grafana-mcp/ks.yaml
  - ./mcp/actual-mcp/ks.yaml
  - ./mcp/obsidian-mcp/ks.yaml
  - ./mcp/unifi-network-mcp/ks.yaml
