---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  settings.yml: |
    use_default_settings: true
    server:
      secret_key: "changeme"
      limiter: false
    search:
      formats:
        - html
        - json
