---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  chartRef:
    kind: OCIRepository
    name: searxng
  interval: 30m
  values:
    controllers:
      searxng:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: 2025.6.25-82e2b775a
            env:
              INSTANCE_NAME: searxng
              BASE_URL: https://search.nebular-grid.space/
              AUTOCOMPLETE: "false"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      app:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames:
          - search.nebular-grid.space
        parentRefs:
          - name: envoy-internal
            namespace: network
