---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux-operator
  interval: 1h
  path: ./clusters/psb/apps/flux-system/flux-operator/app
  prune: false # Never delete this
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: flux-system
  timeout: 5m
  wait: false
