---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./clusters/psb/apps/selfhosted/paperless/app"
  postBuild:
    substitute:
      APP: paperless
      APP_UID: "2000"
      APP_GID: "2000"
      VOLSYNC_CLAIM: paperless-data
      VOLSYNC_CAPACITY: 15Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
