---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.4.5
    digest: sha256:f02e39bf5ab6b0b406a68846d516b0daf5d46ecc9b11d427b7fc3491ddd27ee9
  url: oci://ghcr.io/home-operations/charts/tuppr
