---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recyclarr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: recyclarr
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: "./clusters/psb/apps/downloads/recyclarr/app"
  postBuild:
    substitute:
      APP: recyclarr
      VOLSYNC_CLAIM: recyclarr-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
