---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  # refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      data:
        FRIGAGE_DOORBELL_FRY_EXT_IP: 10.1.4.10
        FRIGATE_DOORBELL_FRY_EXT_USERNAME: "{{ .doorbell_username }}"
        FRIGATE_DOORBELL_FRY_EXT_PASSWORD: "{{ .doorbell_password }}"
        FRIGATE_CAMERA_FRY_EXT_IP: 10.1.4.12
        FRIGATE_CAMERA_FRY_EXT_USERNAME: "{{ .camera_username }}"
        FRIGATE_CAMERA_FRY_EXT_PASSWORD: "{{ .camera_password }}"
  dataFrom:
    - extract:
        key: Camera (fry.ext)
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "camera_$1"
    - extract:
        key: Doorbell (fry.ext)
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "doorbell_$1"
