---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  chartRef:
    kind: OCIRepository
    name: frigate
  interval: 30m
  values:
    controllers:
      frigate:
        pod:
          annotations:
            reloader.stakater.com/auto: "true"
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.1.30.157/24"],
                "mac": "76:fa:11:c0:c9:84"
              }]
          resourceClaims:
            - name: gpu
              resourceClaimTemplateName: frigate-gpu
        containers:
          app:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.17.0@sha256:5be5ce3b79f8b09a52957afea9d4a23ad62c9f077a05d9047e3404eb78c304a8
            envFrom:
              - secretRef:
                  name: frigate-secret
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 200m
                memory: 2Gi
              limits:
                memory: 8Gi
    service:
      frigate:
        ports:
          http:
            appProtocol: kubernetes.io/wss
            port: 5000
          go2rtc:
            primary: true
            port: 1984
          rtsp:
            port: 8554
          webrtc-tcp:
            port: 8555
            protocol: TCP
          webrtc-udp:
            port: 8555
            protocol: UDP
    persistence:
      config:
        existingClaim: frigate
      media:
        type: nfs
        path: /mnt/tank/apps/frigate
        server: asc.internal
        globalMounts:
          - path: /media/frigate
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /dev/shm
      tmpfs:
        type: emptyDir
        advancedMounts:
          frigate:
            app:
              - path: /tmp
                subPath: tmp
    route:
      frigate:
        hostnames:
          - frigate.nebular-grid.space
        parentRefs:
          - name: envoy-internal
            namespace: network

        rules:
          - backendRefs:
              - identifier: frigate
                port: 5000
      go2rtc:
        hostnames:
          - frigate-go2rtc.nebular-grid.space
        parentRefs:
          - name: envoy-internal
            namespace: network

        rules:
          - backendRefs:
              - identifier: frigate
                port: 1984
