---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmcpserver_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: rohlik
spec:
  alias: rohlik
  url: https://mcp.rohlik.cz/mcp
  transport: http
  params:
    extra_headers:
      - rhl-email
      - rhl-pass
