---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memini
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: memini-secret
    creationPolicy: Owner
    template:
      data:
        MEMINI_API_KEY: "{{ .api_key }}"
  dataFrom:
    - extract:
        key: memini
