---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: memini
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.7.28
    digest: sha256:ffcb94681df28970cb03a1bd4953287365ca67853f6a0de2883e5130a277ba5c
  url: oci://registry.erwanleboucher.dev/eleboucher/charts/memini
