---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: memini
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.7.19
    digest: sha256:4c9c9a83ad73ea5210e2009e1039fa1efb2107c38be7aa9262e3d89ef126922d
  url: oci://registry.erwanleboucher.dev/eleboucher/charts/memini
