---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: memini
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v0.7.22
    digest: sha256:31bf537bf57e994a0bb028c4845a8ce771ddd7ff867ea2212ba89f8681c0d474
  url: oci://registry.erwanleboucher.dev/eleboucher/charts/memini
