---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.19.2
    digest: sha256:2fa5fb19284a9070e00d7c7f512c45050e888ef47220f56095fc2959b5c03099
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
