---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.19.1
    digest: sha256:88fcd2caae10594d07435e6198f197b55c108acd179e8880558eb9205adb66a8
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
