---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 87.20.0
    digest: sha256:8fdea132ea9d5cce9caede8ee0cdef7b8ff932b5478d943e4b3d3e3fb47bf544
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
