---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
components:
  - ../../components/flux-alerts
resources:
  - ./namespace.yaml
  - ./descheduler/ks.yaml
  # - ./generic-device-plugin/ks.yaml
  - ./kopiur/ks.yaml
  - ./ksgate/ks.yaml
  - ./reloader/ks.yaml
