---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.28.2
    digest: sha256:484e812908daeac1b84614df333040ffe2eb868f3a7169ffe6c003d566f554e6
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
