---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: konflate-secret
    creationPolicy: Owner
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .webhook_secret }}"
        KONFLATE_APP_CLIENT_ID: "{{ .app_client_id }}"
        KONFLATE_APP_PRIVATE_KEY: "{{ .app_private_key }}"
  data:
    - secretKey: webhook_secret
      remoteRef:
        key: Konflate
        property: webhook secret
    - secretKey: app_client_id
      remoteRef:
        key: Trashbot-9000
        property: app client id
    - secretKey: app_private_key
      remoteRef:
        key: Trashbot-9000
        property: app private key
