---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: attic
spec:
  chartRef:
    kind: OCIRepository
    name: attic
  interval: 30m
  values:
    controllers:
      attic:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 2000
            runAsUser: 2000

        containers:
          app:
            image:
              repository: ghcr.io/zhaofengli/attic
              tag: latest
            env:
              ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64:
                valueFrom:
                  secretKeyRef:
                    name: attic-secret
                    key: ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &httpPort 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            resources:
              requests:
                cpu: 50m
                memory: 256M
              limits:
                memory: 1Gi

    service:
      app:
        ports:
          http:
            port: *httpPort

    persistence:
      config:
        type: configMap
        name: attic-config
        globalMounts:
          - path: /etc/atticd/server.toml
            subPath: server.toml
            readOnly: true
      data:
        existingClaim: attic-data
        globalMounts:
          - path: /var/lib/atticd

    route:
      app:
        hostnames:
          - attic.nebular-grid.space
        parentRefs:
          - name: envoy-internal
            namespace: network
