---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name ${APP}-postgres
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: database-ns
  target:
    name: *name
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        host: "{{ .host }}"
        database: "{{ .database }}"
        url: "{{ .url }}"
  data:
    - secretKey: username
      remoteRef:
        key: ${APP}-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: ${APP}-postgres
        property: password
    - secretKey: host
      remoteRef:
        key: ${APP}-postgres
        property: host
    - secretKey: database
      remoteRef:
        key: ${APP}-postgres
        property: database
    - secretKey: url
      remoteRef:
        key: ${APP}-postgres
        property: url
