---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.15
    digest: sha256:36bf342d0eb628f4bfeb613388ee5bdbae66e4c8e90ba3b6441ad6dbe1780213
  url: oci://ghcr.io/home-operations/charts/litellm-operator
