---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.16
    digest: sha256:b5ee7586b9a0dcecb4c8243bb1de59c4f432fb8eb71b71e6a09f476fedb979ca
  url: oci://ghcr.io/home-operations/charts/litellm-operator
