---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: litellm-operator
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.20
    digest: sha256:b518fabe48e5c48cc3a780c7b23c094737452d7ed4daf243673f1776fb2595d3
  url: oci://ghcr.io/home-operations/charts/litellm-operator
