---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1alpha1.json
apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: mcp-searxng
spec:
  image: docker.io/isokoliuk/mcp-searxng:1.8.0@sha256:787626c360cc00559093416bc701bf029075615da0c67b7026e6bc11c7386f19
  transport: streamable-http
  proxyPort: 8080
  env:
    - name: SEARXNG_URL
      value: http://searxng.selfhosted.svc.cluster.local:8080
    - name: MCP_HTTP_PORT
      value: "8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
