---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: llmkube
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.28
    digest: sha256:1c6765c81a0f424f28b0f5d6abf13e776b2f4f2d1d3f88458e00f825ae62845a
  url: oci://ghcr.io/defilantech/charts/llmkube
