---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: llmkube
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.18
    digest: sha256:4f43a44bbf1d7cdef180d9f075637a8ac2aa29630d620682328e72d628be8d53
  url: oci://ghcr.io/defilantech/charts/llmkube
