---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: llmkube
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.14
    digest: sha256:0927762b099ca29455e9221e5b6d571930d19b2f0ae79f807c9e277c899eb3b2
  url: oci://ghcr.io/defilantech/charts/llmkube
