---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      data:
        PAPERLESS_ADMIN_USER: "{{ .paperless_username }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .paperless_password }}"
        PAPERLESS_SECRET_KEY: "{{ .paperless_secret_key }}"
        PAPERLESS_OCR_LANGUAGE: "{{ .paperless_ocr_langs }}"
  dataFrom:
    - extract:
        key: Paperless
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "paperless_$1"
