---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-${APP}
  namespace: database
spec:
  name: ${APP}
  owner: ${APP}
  cluster:
    name: postgres
