---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-gpu-resource-driver
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: intel-gpu-resource-driver
  interval: 1h
  path: "./clusters/psb/apps/kube-system/intel-gpu-resource-driver/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: false
