---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-tools
  labels:
    app.kubernetes.io/name: immich-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: immich-tools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-tools
    spec:
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: immich-tools
          image: ghcr.io/trash-panda-v91-beta/immich-tools:v0.2.4
          args:
            - "serve"
          env:
            - name: IMMICH_URL
              value: http://immich-server.media.svc.cluster.local:2283
            - name: IMMICH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: immich-tools-secret
                  key: api_key
            - name: PCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: immich-tools-secret
                  key: pcloud_token
            - name: PCLOUD_HOST
              value: eapi.pcloud.com
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: immich-tools-secret
                  key: api_token
            - name: CONFIG
              value: /data/config.toml
            - name: STATE_DIR
              value: /data/state
            - name: FAVORITES_DIR
              value: /favorites
            - name: SYNC_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: immich-tools-config
                  key: sync_interval
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
            - name: favorites
              mountPath: /favorites
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-tools-data
        - name: favorites
          persistentVolumeClaim:
            claimName: immich-favorites
