---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-favorites
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 30Gi
  nfs:
    path: /mnt/tank/stores/photos/favorites
    server: asc.internal
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-favorites
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: ""
  volumeName: immich-favorites
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-tools-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /mnt/tank/stores/photos/immich-tools
    server: asc.internal
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-tools-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: immich-tools-data
