---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 8.4.1
    digest: sha256:580c0b0604ec6a45562e35a553dc3e8f8ef3f1f457abcf54037f93890d239acc
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
