#!/usr/bin/env bash
#MISE description="[bootstrap] Bootstrap Kubernetes (etcd)"
set -euo pipefail

controller=$(talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1)

until output=$(talosctl -n "${controller}" bootstrap 2>&1 || true) && [[ "${output}" == *"AlreadyExists"* ]]; do
  echo "Kubernetes bootstrap in progress, retrying in 5 seconds..."
  sleep 5
done
