---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.0
    digest: sha256:00205e1765c8d39677b9ab613021afbca1aef1caffdd21d8b1b18fc5521ccee0
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
