---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ksgate
spec:
  chartRef:
    kind: OCIRepository
    name: ksgate
  interval: 30m
  values:
    extraArgs:
      - --zap-log-level
      - info
