---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ksgate
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.6.2
    digest: sha256:89c2357f030a92dca37a812e2a7bff2f311fb3711cb2c09012c2bdbb3051ab69
  url: oci://ghcr.io/ksgate/charts/ksgate
