---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: barman-r2
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: barman-r2
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        ACCESS_KEY_ID: "{{ .r2_access_key_id }}"
        SECRET_ACCESS_KEY: "{{ .r2_secret_access_key }}"
        ENDPOINT: "{{ .r2_endpoint }}"
        BUCKET_NAME: "{{ .r2_bucket_name }}"
  dataFrom:
    - extract:
        key: R2 PSB Postgres Bucket
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "r2_$1"
