---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2

  imageName: docker.io/timescale/timescaledb-ha:pg18-all-amd64

  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

  superuserSecret:
    name: postgres-superuser

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: r2-store

  monitoring:
    enablePodMonitor: true

  postgresql:
    shared_preload_libraries:
      - timescaledb
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"

  managed:
    roles: []
