---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-bookworm@sha256:7dafe75a2a0033ae0d91540ce151367aae0c28ef50c8cc6c060092cd22f33b1d

  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

  superuserSecret:
    name: postgres-superuser

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: r2-store

  monitoring:
    enablePodMonitor: true

  postgresql:
    shared_preload_libraries:
      - timescaledb
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"
    extensions:
      - name: timescaledb
        image:
          reference: ghcr.io/shusaan/timescaledb-testing:2.24.0-18-bookworm@sha256:c70de2380b2acc5237a94be662e362694361216373afb04161eb0e76de79a698

  managed:
    roles: []
