---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: enabled
spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-standard-trixie@sha256:81bad466fe006454482678c6c67a24c1e30454b519011e0196cba2e4c83e1e1a

  bootstrap:
    initdb:
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

  superuserSecret:
    name: postgres-superuser

  storage:
    size: 10Gi
    storageClass: openebs-hostpath

  plugins:
    - name: &plugin barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: r2-store

  monitoring:
    enablePodMonitor: true

  postgresql:
    shared_preload_libraries:
      - timescaledb
    parameters:
      timescaledb.telemetry_level: "off"
      max_locks_per_transaction: "128"
    extensions:
      - name: timescaledb
        image:
          reference: ghcr.io/shusaan/timescaledb-testing:2.23.1-18-trixie@sha256:e06e12e4dc1df9d427b22a7cbab19ef9b800552d712a439e948fcc4efacf67d4

  managed:
    roles:
      - name: tracearr
        ensure: present
        login: true
        superuser: false
        disablePassword: false
        passwordSecret:
          name: tracearr-postgres
      - name: immich
        ensure: present
        login: true
        superuser: false
        disablePassword: false
        passwordSecret:
          name: immich-postgres
