---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser
spec:
  refreshInterval: "0"
  target:
    name: postgres-superuser
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: postgres
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: pw
