---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clustergenerator.yaml
  - ./clustersecretstore.yaml
  - ./externalsecret.yaml
  - ./barman-externalsecret.yaml
  - ./objectstore.yaml
  - ./scheduledbackup.yaml
  - ./cluster.yaml
