---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2-store
spec:
  configuration:
    destinationPath: s3://psb-cnpg/
    endpointURL: ${ENDPOINT}
    s3Credentials:
      accessKeyId:
        name: barman-r2
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: barman-r2
        key: SECRET_ACCESS_KEY
    wal:
      compression: zstd
    data:
      compression: gzip
  retentionPolicy: "14d"
