---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Flate

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  filter-changes:
    name: Filter changes
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get changed files
        id: changed-files
        uses: bjw-s-labs/action-changed-files@a9a36fb08ce06db9b02fbd8026cc2c0945eb9841 # v0.6.0
        with:
          patterns: |-
            clusters/**/*

  flate:
    if: ${{ needs.filter-changes.outputs.changed-files != '[]' }}
    name: Flate
    runs-on: ubuntu-latest
    needs:
      - filter-changes
    permissions:
      contents: read
      pull-requests: write
    env:
      FLATE_PATH: ./clusters/psb/flux/cluster
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install flate
        uses: home-operations/flate/action@13917764cfe2966e22510118ccf2f77d3c4d74ba # 0.2.12
        with:
          token: ${{ github.token }}

      - name: Run flate test
        run: flate test all --base ${{ github.event.repository.default_branch }}

      - name: Run flate diff
        id: diff
        run: |-
          diff=$(flate diff all)
          echo "Changes:"
          echo "${diff}"
          {
            echo 'diff<<EOF'
            echo "${diff}"
            echo 'EOF'
          } >> "${GITHUB_OUTPUT}"

      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && steps.diff.outputs.diff != '' }}
        id: app-token
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}

      - name: Add Comment
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          header: flate
          message: |-
            <details open>
              <summary>Changes:</summary>

            ```diff
            ${{ steps.diff.outputs.diff }}
            ```

            </details>
