---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4

      - name: Run checks
        run: mise run check

  lint_success:
    needs:
      - lint
    if: ${{ !cancelled() }}
    name: Lint successful
    runs-on: ubuntu-latest
    steps:
      - name: Check job status
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
